spring:
  output:
    ansi:
      enabled: always

  liquibase:
    enabled: on
    change-log: db/master.yml

  docker:
    compose:
      file: src/main/docker/gamehive.yml
      enabled: on
      lifecycle-management: start_and_stop

  datasource:
    url: jdbc:mysql://localhost:3306/real_estate_rental?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 2b03f3e86209dbade396
            clientSecret: 3ed862b38d8e26113e7977a19fd30f945b23629b
          facebook:
            clientId: 2455619794635990
            clientSecret: 03c9a2ed5f3be5cfe620e4bf7b6bdd9a
            scope:
              - email
              - public_profile
          google:
            clientId: 773953843766-t3hffrvfuuppb7tvh8j43clfdjh23jbt.apps.googleusercontent.com
            clientSecret: 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

#logging:
#  file:
#    name: myLogs.log
#  level:
#    root: debug

token:
  signing:
    key: Q2lyNXNOTENrV1dNRGI2NDlJc1p5bTBxM2p1M2RZeTc1amtmbW1HRnZHST0=
  validity:
    access:
      in:
        minutes: 1000
    refresh:
      in:
        month: 1
file:
  upload-dir: E:\env\fileStorage\fil-rouge