spring:

  output:
    ansi:
      enabled: always

  liquibase:
    enabled: on
    change-log: db/master.yml

  docker:
    compose:
      file: src/main/docker/gamehive.yml
      enabled: on
      lifecycle-management: start_and_stop

  datasource:
    url: jdbc:mysql://localhost:3306/real_estate_rental?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

#logging:
#  file:
#    name: myLogs.log
#  level:
#    root: debug

token:
  signing:
    key: Q2lyNXNOTENrV1dNRGI2NDlJc1p5bTBxM2p1M2RZeTc1amtmbW1HRnZHST0=
  validity:
    access:
      in:
        minutes: 1400
    refresh:
      in:
        month: 1